/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    InspectorPane: typeof import('./src/components/InspectorPane.vue')['default']
    InspectorRow: typeof import('./src/components/InspectorRow.vue')['default']
    InspectorSection: typeof import('./src/components/InspectorSection.vue')['default']
    PreviewPane: typeof import('./src/components/PreviewPane.vue')['default']
    PromptDialog: typeof import('./src/components/PromptDialog.vue')['default']
    RenderPanel: typeof import('./src/components/RenderPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SegmentRail: typeof import('./src/components/SegmentRail.vue')['default']
    TimelinePane: typeof import('./src/components/TimelinePane.vue')['default']
  }
}
